### ISSUE TITLE
Add new metrics *stats_ms*

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/manticoresearch-prometheus#19]
`SHOW STATUS` was recently [improved](https://github.com/manticoresoftware/manticoresearch/pull/2584) and now returns the following new metrics:

```
+ insert_replace_stats_ms_avg
+ insert_replace_stats_ms_max
+ insert_replace_stats_ms_min
+ insert_replace_stats_ms_pct95
+ insert_replace_stats_ms_pct99
+ search_stats_ms_avg
+ search_stats_ms_max
+ search_stats_ms_min
+ search_stats_ms_pct95
+ search_stats_ms_pct99
+ update_stats_ms_avg
+ update_stats_ms_max
+ update_stats_ms_min
+ update_stats_ms_pct95
+ update_stats_ms_pct99
```

The task is to update the exporter accordingly and make sure the nightly test doesn't fail anymore - https://github.com/manticoresoftware/manticoresearch-prometheus/actions/runs/11204801330/job/31143618868

**Comment by KlimTodrik** [comment]
Done in https://github.com/manticoresoftware/manticoresearch-prometheus/commit/40ab837ea4424d83c5a405509cc6a68bdd239aeb
