### ISSUE TITLE
Port mismatch dockerfile vs deployment.yaml

### ISSUE THREAD

**Issue by barryhunter** [manticoresoftware/manticoresearch-prometheus#2]
The dockerfile has
 
    CMD ["php", "-S" ,"0.0.0.0:8081"]

but the example deployment.yaml file 

        prometheus.io/port: "8080"
and
            port: 8080

Surely they should match? probably just update `deployment.yaml` to 8081?

Already the helm chart uses 8081, which is fine
https://github.com/manticoresoftware/manticoresearch-helm/blob/7b818eba7362559885499c745ccc58ca5064ea82/charts/manticoresearch/values.yaml#L140

I only found this, because wanted to setup the prometheus exporter as a sidecar for our original manticore pod (pre the helm chart) and copied from deployment.yaml, which is wrong!

**Comment by KlimTodrik** [comment]
Done https://github.com/manticoresoftware/manticoresearch-prometheus/pull/3
