### ISSUE TITLE
"show tables" response changed column name from "Index" to "Table", which breaks the exporter script

### ISSUE THREAD

**Issue by tc-hsteffen** [manticoresoftware/manticoresearch-prometheus#20]
With latest dev versions of manticore-search we get errors when using the prometheus exporter:

`<b>Fatal error</b>:  Uncaught mysqli_sql_exception: P01: syntax error, unexpected $end, expecting SETTINGS or STATUS near 'STATUS' in /var/www/localhost/metrics/src/Exporter.php:506
Stack trace:
#0 /var/www/localhost/metrics/src/Exporter.php(506): mysqli-&gt;query('SHOW INDEX  STA...')
#1 /var/www/localhost/metrics/src/Exporter.php(441): Exporter-&gt;getMetrics()
#2 /var/www/localhost/metrics/index.php(23): Exporter-&gt;__construct(Object(mysqli))
#3 {main}
  thrown in <b>/var/www/localhost/metrics/src/Exporter.php</b> on line <b>506</b><br />
`

The "show tables" response has somehow changed. In the past there have been two columns: Index, Type
Now the column names are: Table, Type

Thus, when iterating through the rows, the key 'Index' delivers an empty result:

SHOW INDEX ' . $row['Index'] . ' STATUS

which makes the statement incomplete/invalid:  "SHOW INDEX  STATUS"

Tested with Manticore search version="6.3.7 b0bdcb154@24110318 dev (columnar 2.3.1 30ad2d6@24100914) (secondary 2.3.1 30ad2d6@24100914) (knn 2.3.1 30ad2d6@24100914) (buddy v3.0.1)
and using docker.io/manticoresearch/prometheus-exporter:6.3.2.0

**Comment by sanikolaev** [comment]
@tc-hsteffen thanks for letting us know. We are working on fixing it.

**Comment by KlimTodrik** [comment]
Done in https://github.com/manticoresoftware/manticoresearch-prometheus/commit/40ab837ea4424d83c5a405509cc6a68bdd239aeb

**Comment by tc-hsteffen** [comment]
Hi @sanikolaev , I just installed the freshly generated image of https://hub.docker.com/r/manticoresearch/prometheus-exporter/tag 6.3.6.0 - but the fix doesn't seem to be included?

**Comment by KlimTodrik** [comment]
@tc-hsteffen I rebuilt the last image. Try one more time.
Don't forget to pull image before

```
docker pull manticoresearch/prometheus-exporter:6.3.6.0
```

**Comment by tc-hsteffen** [comment]
now I see the changes, could you spend a fresh tag for it please? 
We have  imagePullPolicy: IfNotPresent - so the tag 6.3.6.0 is now vasted :-(
thank you

**Comment by KlimTodrik** [comment]
Done in `manticoresearch/prometheus-exporter:6.3.6.1`
