### ISSUE TITLE
Exporter not working on latest version of prometheus

### ISSUE THREAD

**Issue by EdRamos12** [manticoresoftware/manticoresearch-prometheus#24]
### Compatibility Issue: Exporter Fails with Prometheus >= 3.0.0 Due to Unsupported Content-Type

The ManticoreSearch Prometheus exporter is currently incompatible with recent versions of Prometheus (e.g., >= 3.0.0). This issue is caused by Prometheus now enforcing stricter checks on the Content-Type of scraped targets. The exporter previously worked without issues in versions like 2.49.1, but now fails with the following error:

```bash
time=2024-12-04T16:55:45.068Z level=ERROR source=scrape.go:1585 msg="Failed to determine correct type of scrape target." component="scrape manager" scrape_pool=manticore_exporter target=http://localhost:8081/metrics content_type="text/html; charset=UTF-8" fallback_media_type="" err="received unsupported Content-Type \"text/html; charset=UTF-8\" and no fallback_scrape_protocol specified for target"
```

![image](https://github.com/user-attachments/assets/b4f0c082-61a5-4ecd-8aee-56dda01f3baa)

**Steps to Reproduce:**

1.  Install Prometheus version 3.0.0 or later.
2.  Configure Prometheus to scrape metrics from the ManticoreSearch exporter endpoint.
3.  Observe the scrape failure in Prometheus logs.

___

**Expected Behavior:**  
The ManticoreSearch Prometheus exporter should serve metrics with a `Content-Type` header of `text/plain`, as required by Prometheus for proper scraping.

___

**Actual Behavior:**  
The exporter responds with a `Content-Type` of `text/html; charset=UTF-8`, causing Prometheus to reject the response.

___

**Prometheus Logs:**

```bash
time=2024-12-04T18:02:16.529Z level=ERROR source=scrape.go:1585 msg="Failed to determine correct type of scrape target." component="scrape manager" scrape_pool=manticore_exporter target=http://manticore_exporter:8081/metrics content_type="text/html; charset=UTF-8" fallback_media_type="" err="received unsupported Content-Type \"text/html; charset=UTF-8\" and no fallback_scrape_protocol specified for target"
```

___

**Environment:**

-   Prometheus Version: 3.0.0 (and above)
-   Exporter Version: 6.3.6
-   Operating System: Dockerfile from github repo (php:alpine)

___

**Additional Context:**  
The issue seems to stem from the exporter not setting the `Content-Type` header correctly for the `/metrics` endpoint. According to Prometheus documentation, the exporter should conform to the OpenMetrics format and return a `Content-Type` of `text/plain`.

___

**Suggested Fix:**  
Update the ManticoreSearch Prometheus exporter to ensure that:

1.  The `/metrics` endpoint always returns `Content-Type: text/plain; version=0.0.4`.
2.  Test compatibility with Prometheus >= 3.0.0.

___

**Workaround (Temporary):**  
Users can downgrade Prometheus to version 2.49.1 or earlier, where the exporter works as expected. However, this is not a long-term solution.

![image](https://github.com/user-attachments/assets/a962eeca-2be1-4574-b24a-8e6bc6e360ee)

___

Let me know if additional information or debugging is needed. Thank you for maintaining this project!

**Comment by KlimTodrik** [comment]
Done in 6.3.8.0
