### ISSUE TITLE
Release prom. exporter

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/manticoresearch-prometheus#4]

**Comment by KlimTodrik** [comment]
- [x] be sure that exporter works as expected and exports specific metrics
- [x] check with head of master (we changed `SHOW THREADS` output)
- [x] add new release

**Comment by KlimTodrik** [comment]
Don't forget to switch exporter to version 6.2.13 after new Helm release with new SHOW THREADS syntax support
