### ISSUE TITLE
Metrics name mismatch

### ISSUE THREAD

**Issue by polleuretan** [manticoresoftware/manticoresearch-prometheus#5]
The metric name in the Metadata differs from the metric name in MetricPoint (`manticore_` prefix).
Example:
```
# HELP uptime_seconds Time in secons since start
# TYPE uptime_seconds counter
manticore_uptime_seconds 630365
```
The fix should be pretty straightforward, just depends on maintainers preference - either add the same `manticore_` prefix to the Metadata, or remove it from the MetricPoint.

**Comment by KlimTodrik** [comment]
Done in https://github.com/manticoresoftware/manticoresearch-prometheus/pull/7
