### ISSUE TITLE
All metrics from searchd --status (SHOW STATUS) should be available

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/manticoresearch-prometheus#6]
I had a call with a user who's using another Prometheus exporter for Manticore, because ours doesn't return all metrics from `searchd --status`. The task is revisit the behaviour of the exporter to make sure it can export all metrics from `SHOW STATUS` (and `searchd --status` which, I believe, is a 100% mirror). If we don't have some descriptions for new metrics - no problem, it's still better than a missing metric.

**Comment by KlimTodrik** [comment]
Done in https://github.com/manticoresoftware/manticoresearch-prometheus/pull/7
